import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { DpiaDraft } from "@/lib/gdpr/dpia-generator";

const colors = {
  primary: "#1a1a2e",
  accent: "#7c3aed",
  gray: "#6b7280",
  border: "#e5e7eb",
  lightGray: "#f3f4f6",
  redSoft: "#fee2e2",
  redDark: "#991b1b",
};

const s = StyleSheet.create({
  page: { padding: 44, fontFamily: "Helvetica", fontSize: 10, color: colors.primary, lineHeight: 1.45 },
  coverEyebrow: { fontSize: 9, color: colors.accent, textTransform: "uppercase" as const, letterSpacing: 1, marginBottom: 10 },
  coverTitle: { fontSize: 24, fontFamily: "Helvetica-Bold", marginBottom: 10 },
  coverSubtitle: { fontSize: 12, color: colors.gray, marginBottom: 32 },
  metaBox: { backgroundColor: colors.lightGray, borderRadius: 6, padding: 14, marginBottom: 10 },
  metaLabel: { fontSize: 8, color: colors.gray, textTransform: "uppercase" as const, marginBottom: 3, letterSpacing: 0.5 },
  metaValue: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  sectionEyebrow: { fontSize: 8, color: colors.accent, textTransform: "uppercase" as const, letterSpacing: 1, marginTop: 22, marginBottom: 4 },
  sectionTitle: { fontSize: 14, fontFamily: "Helvetica-Bold", marginBottom: 8, color: colors.primary },
  block: { marginBottom: 14 },
  blockLabel: { fontSize: 9, color: colors.gray, textTransform: "uppercase" as const, letterSpacing: 0.5, marginBottom: 3 },
  blockHeading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  blockText: { fontSize: 10, color: "#374151", lineHeight: 1.5 },
  disclaimer: { fontSize: 9, color: colors.redDark, fontStyle: "italic" as const, marginTop: 18, padding: 12, backgroundColor: colors.redSoft, borderRadius: 4 },
  footer: {
    position: "absolute" as const, bottom: 30, left: 44, right: 44,
    fontSize: 7.5, color: colors.gray, flexDirection: "row", justifyContent: "space-between",
    borderTop: `1 solid ${colors.border}`, paddingTop: 6,
  },
});

export interface DpiaReportMeta {
  controllerName: string;
  processingName: string;
  contactEmail: string;
  assessmentDate: string;
  status: string;
  supervisoryConsulted: boolean;
}

function Block({ label, heading, article, text }: { label: string; heading: string; article: string; text: string }) {
  return (
    <View style={s.block} wrap={false}>
      <Text style={s.blockLabel}>{label} · {article}</Text>
      <Text style={s.blockHeading}>{heading}</Text>
      <Text style={s.blockText}>{text || "—"}</Text>
    </View>
  );
}

export function DpiaReport({ meta, draft }: { meta: DpiaReportMeta; draft: DpiaDraft }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.coverEyebrow}>Data Protection Impact Assessment</Text>
        <Text style={s.coverTitle}>DPIA — GDPR Article 35</Text>
        <Text style={s.coverSubtitle}>
          Regulation (EU) 2016/679 · Controller-side obligation when processing is likely high-risk to data subjects
        </Text>

        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Controller</Text>
          <Text style={s.metaValue}>{meta.controllerName}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Processing operation</Text>
          <Text style={s.metaValue}>{meta.processingName}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Contact</Text>
          <Text style={s.metaValue}>{meta.contactEmail}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Assessment date</Text>
          <Text style={s.metaValue}>{meta.assessmentDate}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Status</Text>
          <Text style={s.metaValue}>{meta.status}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Supervisory authority consulted (Art. 36)</Text>
          <Text style={s.metaValue}>{meta.supervisoryConsulted ? "Yes" : "No"}</Text>
        </View>

        <View style={s.disclaimer}>
          <Text>
            This DPIA draft was generated by AIComply from a short processing description. GDPR Art. 35(2)
            requires that the DPO be consulted when designated. Art. 36(1) requires prior consultation with
            the supervisory authority when residual risk remains high. This document MUST be reviewed and
            completed by qualified data protection counsel before it is relied upon. AIComply does not warrant
            legal compliance.
          </Text>
        </View>

        <View style={s.footer} fixed>
          <Text>AIComply — DPIA (GDPR Article 35)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 1</Text>
        <Text style={s.sectionTitle}>Systematic Description of Processing</Text>

        <Block label="1.1 Processing description" heading="Nature, scope, and context of the processing" article="Art. 35(7)(a)" text={draft.processing_description} />
        <Block label="1.2 Purposes" heading="Specific purposes for which the data is used" article="Art. 35(7)(a)" text={draft.processing_purposes} />
        <Block label="1.3 Data categories" heading="Personal data categories (Art. 9 special categories flagged)" article="Art. 4(1) · Art. 9" text={draft.data_categories} />
        <Block label="1.4 Data subjects" heading="Categories of data subjects" article="Art. 4(1)" text={draft.data_subjects} />
        <Block label="1.5 Recipients" heading="Parties that receive the data" article="Art. 4(9)" text={draft.recipients} />
        <Block label="1.6 Retention" heading="Retention period with justification" article="Art. 5(1)(e)" text={draft.retention_period} />
        <Block label="1.7 International transfers" heading="Transfers outside the EEA and safeguards" article="Chapter V" text={draft.international_transfers} />

        <View style={s.footer} fixed>
          <Text>AIComply — DPIA (GDPR Article 35)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 2</Text>
        <Text style={s.sectionTitle}>Necessity &amp; Proportionality</Text>

        <Block label="2.1 Lawful basis" heading="Art. 6 basis + Art. 9 exception if special category data" article="Art. 6 · Art. 9" text={draft.legal_basis} />
        <Block label="2.2 Necessity" heading="Evidence-based justification for the processing" article="Art. 35(7)(b)" text={draft.necessity_justification} />
        <Block label="2.3 Proportionality" heading="Balancing test vs data subject intrusion" article="Art. 35(7)(b)" text={draft.proportionality_assessment} />
        <Block label="2.4 Data minimisation" heading="Measures to collect / retain only what is necessary" article="Art. 5(1)(c)" text={draft.data_minimisation} />

        <Text style={s.sectionEyebrow}>Section 3</Text>
        <Text style={s.sectionTitle}>Risks to Rights &amp; Freedoms</Text>

        <Block label="3.1 Rights implicated" heading="Charter + GDPR-protected rights at risk" article="Art. 35(7)(c)" text={draft.rights_at_risk} />
        <Block label="3.2 Risk scenarios" heading="Concrete harm scenarios with likelihood &times; severity" article="Art. 35(7)(c)" text={draft.risk_scenarios} />
        <Block label="3.3 Likelihood &amp; severity" heading="Methodology + residual risk" article="Art. 35(7)(c)" text={draft.likelihood_severity} />

        <View style={s.footer} fixed>
          <Text>AIComply — DPIA (GDPR Article 35)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 4</Text>
        <Text style={s.sectionTitle}>Mitigation Measures</Text>

        <Block label="4.1 Technical measures" heading="Encryption, access control, logging, pseudonymisation" article="Art. 32 · Art. 35(7)(d)" text={draft.technical_measures} />
        <Block label="4.2 Organisational measures" heading="Policies, training, RACI, vendor oversight" article="Art. 32 · Art. 28" text={draft.organisational_measures} />
        <Block label="4.3 Data subject rights" heading="How Arts. 15-22 are satisfied (with SLA)" article="Arts. 15-22" text={draft.data_subject_rights} />
        <Block label="4.4 Breach procedure" heading="Detection, notification, timeline" article="Art. 33 · Art. 34" text={draft.breach_procedure} />

        <Text style={s.sectionEyebrow}>Section 5</Text>
        <Text style={s.sectionTitle}>DPO &amp; Supervisory Consultation</Text>

        <Block label="5.1 DPO consultation" heading="Involvement of the DPO + prior consultation posture" article="Art. 35(2) · Art. 36" text={draft.dpo_consultation} />

        <View style={s.disclaimer}>
          <Text>
            If residual risk remains high after the measures above, the controller must consult the
            supervisory authority per Art. 36(1) BEFORE starting the processing. Keep evidence of the
            consultation and its outcome with this DPIA.
          </Text>
        </View>

        <View style={s.footer} fixed>
          <Text>AIComply — DPIA (GDPR Article 35)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
