import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { FriaDraft } from "@/lib/eu-ai-act/fria-generator";

const colors = {
  primary: "#1a1a2e",
  accent: "#0ea5e9",
  gray: "#6b7280",
  border: "#e5e7eb",
  lightGray: "#f3f4f6",
  white: "#ffffff",
  redSoft: "#fee2e2",
  redDark: "#991b1b",
};

const s = StyleSheet.create({
  page: { padding: 44, fontFamily: "Helvetica", fontSize: 10, color: colors.primary, lineHeight: 1.45 },

  coverEyebrow: { fontSize: 9, color: colors.accent, textTransform: "uppercase" as const, letterSpacing: 1, marginBottom: 10 },
  coverTitle: { fontSize: 24, fontFamily: "Helvetica-Bold", marginBottom: 10 },
  coverSubtitle: { fontSize: 12, color: colors.gray, marginBottom: 32 },

  metaBox: { backgroundColor: colors.lightGray, borderRadius: 6, padding: 14, marginBottom: 10 },
  metaLabel: { fontSize: 8, color: colors.gray, textTransform: "uppercase" as const, marginBottom: 3, letterSpacing: 0.5 },
  metaValue: { fontSize: 11, fontFamily: "Helvetica-Bold" },

  sectionEyebrow: { fontSize: 8, color: colors.accent, textTransform: "uppercase" as const, letterSpacing: 1, marginTop: 22, marginBottom: 4 },
  sectionTitle: { fontSize: 14, fontFamily: "Helvetica-Bold", marginBottom: 8, color: colors.primary },

  block: { marginBottom: 16 },
  blockLabel: { fontSize: 9, color: colors.gray, textTransform: "uppercase" as const, letterSpacing: 0.5, marginBottom: 3 },
  blockHeading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  blockText: { fontSize: 10, color: "#374151", lineHeight: 1.5 },

  disclaimer: { fontSize: 9, color: colors.redDark, fontStyle: "italic" as const, marginTop: 18, padding: 12, backgroundColor: colors.redSoft, borderRadius: 4 },

  footer: {
    position: "absolute" as const,
    bottom: 30,
    left: 44,
    right: 44,
    fontSize: 7.5,
    color: colors.gray,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: `1 solid ${colors.border}`,
    paddingTop: 6,
  },
});

export interface FriaReportMeta {
  deployerName: string;
  systemName: string;
  contactEmail: string;
  assessmentDate: string;
  status: string;
}

function Block({
  label,
  heading,
  article,
  text,
}: {
  label: string;
  heading: string;
  article: string;
  text: string;
}) {
  return (
    <View style={s.block} wrap={false}>
      <Text style={s.blockLabel}>
        {label} · {article}
      </Text>
      <Text style={s.blockHeading}>{heading}</Text>
      <Text style={s.blockText}>{text || "—"}</Text>
    </View>
  );
}

export function FriaReport({
  meta,
  draft,
}: {
  meta: FriaReportMeta;
  draft: FriaDraft;
}) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.coverEyebrow}>Fundamental Rights Impact Assessment</Text>
        <Text style={s.coverTitle}>FRIA — Article 27 EU AI Act</Text>
        <Text style={s.coverSubtitle}>
          Regulation (EU) 2024/1689 · High-risk deployer obligation · Applicable from 2 August 2026
        </Text>

        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Deployer</Text>
          <Text style={s.metaValue}>{meta.deployerName}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>AI System Assessed</Text>
          <Text style={s.metaValue}>{meta.systemName}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Contact</Text>
          <Text style={s.metaValue}>{meta.contactEmail}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Assessment Date</Text>
          <Text style={s.metaValue}>{meta.assessmentDate}</Text>
        </View>
        <View style={s.metaBox}>
          <Text style={s.metaLabel}>Status</Text>
          <Text style={s.metaValue}>{meta.status}</Text>
        </View>

        <View style={s.disclaimer}>
          <Text>
            This FRIA draft was generated by AIComply from a brief system description. Article 27(3) of
            the EU AI Act requires the deployer to notify the national market surveillance authority
            upon completion. This document MUST be reviewed and completed by a qualified Data Protection
            Officer or privacy counsel before notification. AIComply does not warrant legal compliance.
          </Text>
        </View>

        <View style={s.footer} fixed>
          <Text>AIComply — FRIA (Article 27 EU AI Act)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 1</Text>
        <Text style={s.sectionTitle}>Deployer Processes &amp; Context of Use</Text>

        <Block
          label="1.1 System description"
          heading="Narrative of the deployer's processes"
          article="Art. 27(1)(a)"
          text={draft.system_description}
        />
        <Block
          label="1.2 Deployment purpose"
          heading="Operational objective and legitimate aim"
          article="Art. 27(1)(a)"
          text={draft.deployment_purpose}
        />
        <Block
          label="1.3 Duration"
          heading="Period over which the system will be used"
          article="Art. 27(1)(b)"
          text={draft.deployment_duration}
        />
        <Block
          label="1.4 Frequency of use"
          heading="Cadence of decisions affecting natural persons"
          article="Art. 27(1)(b)"
          text={draft.frequency_of_use}
        />
        <Block
          label="1.5 Affected groups"
          heading="Categories of natural persons or groups likely to be affected"
          article="Art. 27(1)(c)"
          text={draft.affected_groups}
        />

        <View style={s.footer} fixed>
          <Text>AIComply — FRIA (Article 27 EU AI Act)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 2</Text>
        <Text style={s.sectionTitle}>Risks to Fundamental Rights</Text>

        <Block
          label="2.1 Rights implicated"
          heading="Charter articles and specific fundamental rights at risk"
          article="Art. 27(1)(d)"
          text={draft.rights_at_risk}
        />
        <Block
          label="2.2 Harm scenarios"
          heading="Concrete failure modes and resulting harm"
          article="Art. 27(1)(d)"
          text={draft.harm_scenarios}
        />

        <Text style={s.sectionEyebrow}>Section 3</Text>
        <Text style={s.sectionTitle}>Human Oversight (Art. 14)</Text>

        <Block
          label="3.1 Oversight measures"
          heading="How human reviewers will monitor, override and interpret outputs"
          article="Art. 27(1)(e) · Art. 14"
          text={draft.oversight_measures}
        />
        <Block
          label="3.2 Oversight personnel"
          heading="Roles, competencies, and training requirements"
          article="Art. 27(1)(e) · Art. 14(4)"
          text={draft.oversight_personnel}
        />

        <View style={s.footer} fixed>
          <Text>AIComply — FRIA (Article 27 EU AI Act)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Section 4</Text>
        <Text style={s.sectionTitle}>Mitigation if Risks Materialise</Text>

        <Block
          label="4.1 Mitigation measures"
          heading="Actions to correct, suspend, or remediate harmful outcomes"
          article="Art. 27(1)(f)"
          text={draft.mitigation_measures}
        />
        <Block
          label="4.2 Escalation procedure"
          heading="Operator → manager → DPO → authority path"
          article="Art. 27(1)(f)"
          text={draft.escalation_procedure}
        />

        <Text style={s.sectionEyebrow}>Section 5</Text>
        <Text style={s.sectionTitle}>Governance &amp; Complaints</Text>

        <Block
          label="5.1 Governance framework"
          heading="Internal governance, logging, review cadence"
          article="Art. 27(1)(f) · Art. 26 · Art. 12"
          text={draft.governance_framework}
        />
        <Block
          label="5.2 Complaint mechanism"
          heading="How affected persons can seek explanations and lodge complaints"
          article="Art. 26(6)"
          text={draft.complaint_mechanism}
        />

        <View style={s.disclaimer}>
          <Text>
            Upon completion, this FRIA must be notified to the national market surveillance authority
            using the template to be provided by the AI Office per Article 27(5). Keep evidence of
            notification for the duration of system use.
          </Text>
        </View>

        <View style={s.footer} fixed>
          <Text>AIComply — FRIA (Article 27 EU AI Act)</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
